### PR TITLE
Mustard badge added. Fixes #253

### LINKED ISSUE #253: Add mint-badge mustard modificator
screen shot 2015-09-04 at 17 15 58

### PR DESCRIPTION
**Pull request by kdzwinel**
`mint-badge--alt`:
screen shot 2015-09-07 at 16 47 45

and in action:
screen shot 2015-09-07 at 16 47 36

### CODE REVIEW

**Comment by mr-mig** [comment]
I do not like `alt`. It seems non-semantic for me

**Comment by kdzwinel** [comment]
We were discussing it with Michal and couldn't come up with anything better. We could call it 'mustard' reusing color name, but that's also imperfect. Any ideas?

**Comment by mr-mig** [comment]
alert?

**Comment by mr-mig** [comment]
Let's steal from masters: http://v4-alpha.getbootstrap.com/components/label/
`success`, `info`, `warning`, `error`, `alert`, etc

**Comment by vergilius** [comment]
I have feeling that in future we might need badge-per-basic-color, and using bootstrap's names might be limiting, WDYT @mr-mig?

**Comment by kdzwinel** [comment]
I'm also wondering if our default here is OK (by default badge is red/peach), maybe the default badge should be black? And then it would make some sense to use `error` for red and `warning` for yellow.

**Comment by aju** [comment]
@kdzwinel +1 for the idea

**Comment by kdzwinel** [comment]
names updated. Now the default badge is white and there are two variations: `--error` and `--warning`.

**Comment by aju** [comment]
:ok:

**Comment by vergilius** [comment]
:+1:

**Comment by matzimowski** [comment]
nice branch name :older_man:

**Pull request closed without merging**
