### PR TITLE
Update gray secondary light color and merge gray secondary light and alt light

### PR DESCRIPTION
**Pull request by matzimowski**
before:
screen shot 2016-06-28 at 13 47 39

after:
screen shot 2016-06-28 at 13 42 38

### CODE REVIEW

**Comment by vergilius** [comment]
nice 🍂 🏭 🐼  👍 
image

**Comment by matzimowski** [comment]
@vergilius LOVE YA AND UR PICS

**Comment by aju** [comment]
maybe simple `$grayLight` ?

**Comment by aju** [comment]
OK

**Pull request merged**
