### PR TITLE
Update question icon

### PR DESCRIPTION
**Pull request by matzimowski**
before:
screen shot 2017-02-13 at 19 09 31

after:
screen shot 2017-02-13 at 19 09 35

### CODE REVIEW

**Comment by vergilius** [comment]
was it optimized? looks huge compared to old one

**Comment by matzimowski** [comment]
@vergilius you are right, i will try to optimise it first

**Comment by kdzwinel** [comment]
Yep, looking at both icons the new one shouldn't be much more complicated than the previous one.

**Comment by matzimowski** [comment]
@vergilius @kdzwinel optimized using https://jakearchibald.github.io/svgomg/

**Pull request merged**
