### PR TITLE
Make it possible to disable animations in accordion - a11y fix

### PR DESCRIPTION
**Pull request by ElaLukaszewicz**
disableAnimations

### CODE REVIEW

**Review by Malinicz — APPROVED** [review]
👏

**Review by coderitual — COMMENTED** [review]
Thanks @ElaKrk , please let me check if component behaves correctly and doens' leak. We have some event listeners on transition end.

**Review by matzimowski — APPROVED** [review]
lgtm 👏

**Review by matzimowski — APPROVED** [review]

**Comment by coderitual** [comment]
Hey @ElaLukaszewicz I handled reduced motion in js as well. We need it to handle properly responsiveness in expanded state and hidden attribute in collapse state. Also we would use this util in another components if needed.

**Review by anna-wro — APPROVED** [review]

**Review by coderitual — APPROVED** [review]

**Review by matzimowski — APPROVED** [review]

**Pull request merged**
