### PR TITLE
Update header secondary

### PR DESCRIPTION
**Pull request by aju**
close https://github.com/brainly/style-guide/issues/448
screen shot 2016-07-08 at 09 54 13

### CODE REVIEW

**Comment by aju** [comment]
It makes https://github.com/brainly/style-guide/issues/429 invalid

**Comment by kdzwinel** [comment]
not related, but xsmall primary light is missing from the screenshot, can you add it?

**Comment by aju** [comment]
@kdzwinel updated!
screen shot 2016-07-08 at 10 02 57

**Comment by kdzwinel** [comment]
ok

**Pull request merged**
