### PR TITLE
Updated labels

### PR DESCRIPTION
**Pull request by matzimowski**
closes https://github.com/brainly/style-guide/issues/266

screen shot 2015-09-09 at 17 46 20

### CODE REVIEW

**Comment by mr-mig** [comment]
`Alt` is completely non-semantica in this case.

**Comment by vergilius** [comment]
how about changing these two colors? lets have `secondary` with darker one, and `inactive` with lighter.
whyt @mr-mig @matzimowski ?

**Comment by mr-mig** [comment]
@vergilius I do not get it. What colors do you want to change?
`--secondary` is non semantic as well :)
Maybe its a good time to review the naming for labels

**Comment by matzimowski** [comment]
@vergilius @mr-mig updated

**Comment by mr-mig** [comment]
LGTM :+1:

**Comment by aju** [comment]
:ok:

**Pull request merged**
