### PR TITLE
Remove mint-checkbox-label - use mint-label instead

### LINKED ISSUE #299: Revisit checkbox implementation
`mint-checkbox` implementation has 2 issues:

* The layout is based on inline-block, so centering is an issue
* `rem`-based offsets do not scale with the basic font size change

### PR DESCRIPTION
**Pull request by aju**
closes #299

### CODE REVIEW

**Comment by vergilius** [comment]
:+1:

**Comment by kdzwinel** [comment]
ok

**Comment by mr-mig** [comment]
I'd note that this is a breaking change somewhere.

**Comment by aju** [comment]
I updated version of style guide accordingly

**Pull request merged**
