### PR TITLE
Avatar xl

### PR DESCRIPTION
**Pull request by kdzwinel**
screen shot 2016-04-19 at 10 25 25

Review with [w=1](https://github.com/brainly/style-guide/pull/714/files?w=1)

Breaking change because:
- big avatar becomes large avatar
- large avatar becomes xxlarge avatar
- xlarge avatar is the new one (64/60 px)

### CODE REVIEW

**Comment by matzimowski** [comment]
LOVE KROVE
👍

**Comment by vergilius** [comment]
finally 👏 

🍞  + 🍗  = 🍔

**Comment by vergilius** [comment]
👍

**Comment by aju** [comment]
+1

**Pull request merged**
