### PR TITLE
Rename home-button to mint-home-button. Fixes #159

### LINKED ISSUE #159: home-button component should be called mint-home-button
:lollipop:

### PR DESCRIPTION
**Pull request by kdzwinel**

### CODE REVIEW

**Comment by mr-mig** [comment]
All the headers should be updated I believe
:+1:

**Comment by matzimowski** [comment]
:+1:

**Comment by kdzwinel** [comment]
Yep, it's a breaking change.

**Comment by kdzwinel** [comment]
Fixed in v3.0.0

**Pull request closed without merging**
