### PR TITLE
Text component new color system

### PR DESCRIPTION
**Pull request by domidomi**
Applied new color system to following components: Text, TextBit, Link, Headline
New color props:
Screenshot 2021-12-01 at 17 09 06

### CODE REVIEW

**Comment by coderitual** [comment]
hey @domidomi , didn't we agree that all text components will use all text color tokens (I am referring to screenshot)? Otherwise we won't have proper connection between style guide and figma since new text tokens were meant to solve exactly this problem. We can sync about that.

**Comment by domidomi** [comment]
@coderitual Yeah, I just talked about that with Olga. I was mislead by these color maps for each component https://www.figma.com/file/kkXyr1MSGTnlyQZTu12coA/%5BDS%5D-Colors?node-id=1230%3A61314. We are going to discuss further today

**Comment by coderitual** [comment]
hey @domidomi , please accept chromatic baselines and add reviewers to chromatic UI review if you think all visual changes are ready and on purpose :)

**Comment by domidomi** [comment]
@clxandstuff został tylko Twój approve na UI review :)

**Comment by clxandstuff** [comment]
@domidomi
I will check tomorrow morning.

**Review by clxandstuff — APPROVED** [review]

**Pull request merged**
