### PR TITLE
Feature/fix code style

### PR DESCRIPTION
**Pull request by aju**
This introduces breaking changes to mixins names (used as well in symfony) and to variables names like $include-html

### CODE REVIEW

**Comment by aju** [comment]
Please as well install plugin for you idea thats supports scss-lint

**Comment by matzimowski** [comment]
:+1: :older_man:  => :older_woman:

**Comment by mr-mig** [comment]
I will kill myself rebasing VR

**Comment by mr-mig** [comment]
Can we do it afterwards? I have like 15+ commits already

**Comment by aju** [comment]
@mr-mig I will help you with rebase

**Comment by kdzwinel** [comment]
LGTM

**Comment by mr-mig** [comment]
I will revert this change if you merge it, cause it is a blocker for me

**Comment by vergilius** [comment]
:+1:

**Comment by aju** [comment]
Ok I will close this one and copy just scss-lint updated setting from this one

**Pull request closed without merging**
