### PR TITLE
Update labels

### PR DESCRIPTION
**Pull request by aju**
closes https://github.com/brainly/style-guide/issues/630
closes https://github.com/brainly/style-guide/issues/692

screen shot 2016-07-25 at 11 32 00

### CODE REVIEW

**Comment by matzimowski** [comment]
I lIKE IT
WELL DONE
OK

**Comment by kdzwinel** [comment]
why `--light` `--inactive` and `--full-width` were removed?

Also, since we have a new modifier (`--align-top`) we should show in the docs both: modified and unmodified behaviour (there is no multiline example showing icon in the middle).

**Comment by aju** [comment]
`--light` is same as default now
`--inactive ` is same as `sg-label--secondary
`--full-width` can't find usage in symfony, style guide(docs) or web client

**Comment by aju** [comment]
@kdzwinel docs showing `aling-top` updated 
screen shot 2016-07-25 at 12 20 50

**Comment by kdzwinel** [comment]
👍

**Pull request merged**
