### PR TITLE
Exclude "default" type from className

### PR DESCRIPTION
**Pull request by seahindeniz**
I think there is no point having the `default` as a class name.

I would like to suggest having a boolean based `type` checking since there is no additional `type` than `strong` but that might cause backward compatibility issues and may require additional changes

Before:
image

After:
image

### CODE REVIEW

**Comment by seahindeniz** [comment]
Hi
Should I close this PR if it breaks something?

**Review by matzimowski — APPROVED** [review]

**Review by bartoszlorek — APPROVED** [review]
we have one occurrence of this modifier in our main repo so we will remove it after 🤙

**Comment by matzimowski** [comment]
@bartoszlorek i've seen it, seem to be not needed

**Comment by matzimowski** [comment]
@seahindeniz thanks for your contribution 🙏

**Pull request merged**
