### PR TITLE
Run scss-lint from docker

### LINKED ISSUE #297: Add scss-lint to docker and script to run it
Tralalalala :dancer:

### PR DESCRIPTION
**Pull request by aju**
closes #297

### CODE REVIEW

**Comment by mr-mig** [comment]
Cool! 
Can we integrate it with the plugin in IDEA somehow?

**Comment by aju** [comment]
@mr-mig I will try :)

**Comment by marcinb** [comment]
:+1: nice

**Comment by aju** [comment]
@mr-mig I don't think its possible to force this plugin to run from docker (at least I was not able to configure it)

**Pull request merged**
