### PR TITLE
Reseted default styles for tags

### PR DESCRIPTION
**Pull request by matzimowski**
- link decoration reseted
 - margin and padding of headings and paragraph

closes https://github.com/brainly/style-guide/issues/343

### CODE REVIEW

**Comment by kdzwinel** [comment]
Lets move this changes to basics. normalize is a 3rd party library, we want to be able to update it in the future.

**Comment by aju** [comment]
I agree with Konrad - we should not touch it (I know we did but there was no other way)

**Comment by matzimowski** [comment]
If its a 3rd party, it should come from node_modules

**Comment by matzimowski** [comment]
We will move it :crying_cat_face:

**Comment by aju** [comment]
https://github.com/brainly/style-guide/issues/345

**Comment by matzimowski** [comment]
@aju @kdzwinel done

**Comment by aju** [comment]
:ok:

**Comment by kdzwinel** [comment]
Ack

**Pull request merged**
