### PR TITLE
minor edit to text under the More section

### PR DESCRIPTION
**Pull request by serahrono**

### CODE REVIEW

**Comment by burakukula** [comment]
@serahrono thank you very much for contributing! 🙂
There is a minor complaint from our prettier.
```
170:34  error  Delete `·`  prettier/prettier`
```
If you could have a look and adjust it, we would be good to go. 🙂

**Comment by burakukula** [comment]
Hey @serahrono! 🙂any updates over here? Do you need any help from our side?

**Comment by serahrono** [comment]
hello @burakukula 👋 my edit was primarily the addition of space between 'on' and 'GitHub', but prettier considers that too many spaces and throws the error. Correcting it at this point would mean reverting the change in this PR, and having text served without space.

**Comment by burakukula** [comment]
@serahrono Hey! ok, small trick in `jsx` would be to insert space like follows:
```
{' '}
```
So, in this case, you can insert space in that form like follows:

```
If you&apos;d like to learn more about this project, report a bug or contribute check it out on{' '}
```

Hope this will help. 🙂

**Comment by coderitual** [comment]
Hey @serahrono, I am closing PR as no changes where made. Thanks for the PR and if you want to continue on this, following advice from @burakukula please let me know or open another PR.

**Pull request closed without merging**
