### PR TITLE
Fix image inside avatar

### PR DESCRIPTION
**Pull request by matzimowski**
closes https://github.com/brainly/style-guide/issues/671

no visual changes in style-guide

### CODE REVIEW

**Comment by aju** [comment]
OK

**Comment by kdzwinel** [comment]
no idea, what this is about - @vergilius can you still reproduce it? can you provide screenshots?

**Comment by vergilius** [comment]
I see no difference now, and cannot reproduce it - it possibly was an issue during rebranding on question page with old styles.

**Comment by matzimowski** [comment]
@vergilius so i can close the issue and close this PR?

**Comment by vergilius** [comment]
please do so 👍

**Pull request closed without merging**
