### PR TITLE
Feature/refactor mint icon

### PR DESCRIPTION
**Pull request by aju**
closes https://github.com/brainly/style-guide/issues/472
closes https://github.com/brainly/style-guide/issues/444
closes https://github.com/brainly/style-guide/issues/419
closes https://github.com/brainly/style-guide/issues/356

This is breaking change.
Update `mint-icon` sizes needs to  be set using `--xXX` modifier (--small, --fluid etc are removed!) and `mint-icon-as-button` - `__hole` needs to be added

### CODE REVIEW

**Comment by kdzwinel** [comment]
Looks mostly OK, only thing I found is that overlayed boxes are broken:

screen shot 2015-10-28 at 01 26 50

Lets also remember about adding a section to the docs that shows all icon sizes.

**Comment by mr-mig** [comment]
Can you please add screenshots for opera mini?

**Comment by kdzwinel** [comment]
screen shot 2015-10-28 at 13 57 43
screen shot 2015-10-28 at 13 57 58

**Comment by kdzwinel** [comment]
OK

**Comment by mr-mig** [comment]
:ship:

**Pull request merged**
