### PR TITLE
Added guidelines.md

### PR DESCRIPTION
**Pull request by mr-mig**
Added info from #244

### CODE REVIEW

**Comment by mr-mig** [comment]
Shall it be contributing.md instead?

**Comment by aju** [comment]
@mr-mig I think so. Other than that :+1:

**Comment by vergilius** [comment]
nice :+1:

**Comment by mr-mig** [comment]
Updated the document:
 - Moved dev-related stuff to Contributing.md
 - Added table of contents
 - Added modifier dictionaty decision

**Comment by aju** [comment]
:ok:

**Comment by kdzwinel** [comment]
lgtm

**Comment by matzimowski** [comment]
cool! :+1: :lollipop:

**Pull request merged**
