### PR TITLE
Refactored gutter mixin

### PR DESCRIPTION
**Pull request by mr-mig**
`$layoutDefaultPadding` -> `gutter(1)`

### CODE REVIEW

**Comment by mr-mig** [comment]
THE QUESTION: do we really like `gutter(1 / 4) ` and `rhythm(1 / 2)`? 
Maybe `gutter(0.25)` and `rhythm(0.5)` is better?

**Comment by aju** [comment]
`gutter(0.25)`
:+1:

**Comment by kdzwinel** [comment]
I'm OK with both, lets just be consistent. 
If layoutDefaultPadding is not meant to be used directly anymore can we somehow make it 'private'?

**Comment by mr-mig** [comment]
AFAIK there is no way to make it private

**Comment by mr-mig** [comment]
I will update gutter and rhythm to decimals in a separate PR

**Comment by kdzwinel** [comment]
If you put it inside the mixin it won't be global, not sure if that's the only place where it's being used though.

**Comment by mr-mig** [comment]
If I put it in mixin - it won't be a part of the global config (and it should)

**Comment by kdzwinel** [comment]
:+1:

**Pull request merged**
