### PR TITLE
Refactor text bit

### LINKED ISSUE #241: text-bit--large?
http://brainly.com/login page uses two undocumented size versions of text-bit with font-size 72px and 80px . IMO we should ditch one of these and add the second one to the styleguide.

@aju WDYT?

screen shot 2015-09-02 at 16 00 39

### PR DESCRIPTION
**Pull request by aju**
closes #241
screen shot 2015-09-09 at 10 23 58
screen shot 2015-09-09 at 10 24 08
screen shot 2015-09-09 at 10 24 22

### CODE REVIEW

**Comment by matzimowski** [comment]
:+1: makes sense
:dancers: :dango: :dog2:

**Comment by vergilius** [comment]
:+1:

**Comment by mr-mig** [comment]
LGTM :+1:

**Comment by aju** [comment]
This is breaking change!

**Pull request merged**
