### PR TITLE
SelectMenu bugfixes

### PR DESCRIPTION
**Pull request by domidomi**
- Do not block pointer events on touch screens so triggers work properly
- Fix popup position
- Fix focus management
- Indicate hover on checkbox when hovering option

### CODE REVIEW

**Comment by coderitual** [comment]
thanks @domidomi I will take a look tomorrow morning.

**Comment by coderitual** [comment]
Hey @domidomi couple issues here:
- documentation should always start from presenting component (I am referring to the comment about component being controlled)
- In default story i cannot select item
- There is something wrong with positioning of the popup on our docs page

I will get back to the mobile testing once those are addressed.

https://user-images.githubusercontent.com/8572321/234787429-4709034b-73b8-4da3-a218-74d0d2386c2f.mp4

**Comment by domidomi** [comment]
> Hey @domidomi couple issues here:
> 
> * documentation should always start from presenting component (I am referring to the comment about component being controlled)
> * In default story i cannot select item
> * There is something wrong with positioning of the popup on our docs page
> 
> I will get back to the mobile testing once those are addressed.
> 
>  CleanShot.2023-04-27.at.09.13.30.mp4

@coderitual All fixed now!

**Comment by coderitual** [comment]
hey @domidomi  I found 2 issues:
- not enough space around component in stories
CleanShot 2023-05-11 at 12 52 59

- When using keyboard, there is some jump during animation
https://github.com/brainly/style-guide/assets/8572321/64bb9d12-892f-4c31-b89c-6f569d874b39

**Review by coderitual — APPROVED** [review]
Hey @domidomi , issues from my comment https://github.com/brainly/style-guide/pull/2721#issuecomment-1543777423 can be fixed in separate PR. Let's merge this one so we can double check if everything is ok on form component.

**Pull request merged**
