### PR TITLE
Add std-icons to exported icon type

### PR DESCRIPTION
**Pull request by matzimowski**
to make it possible to use it i.e. in `Label`

```
import Label, {ICON_TYPE} from 'style-guide/src/components/labels/Label';

<Label
    iconType={ICON_TYPE.STD_HEART}
/>
```

### CODE REVIEW

**Comment by matzimowski** [comment]
@vergilius to other way would be to export it from Label, IconAsButton as so on, wdyt?

**Comment by vergilius** [comment]
I don't have enough expertise to tell you how to do it properly, just noticed exporting two separate (though it may be the right way :O) things under one name

**Comment by matzimowski** [comment]
hm, not sure what's the best way to do it here. but since `IconTypeType` accepts both TYPE and STD_TYPE it looked good to me.
anyway, it's an intermediate step, later on STD_ICON will replace renamed to ICON

**Comment by maciekbb** [comment]
Don't we prefer to relay on flow type instead of importing consts?

**Comment by matzimowski** [comment]
@maciekbb we do and we will, but 90% of our codebase doesn't use it and it's much easier to refactor it still using const.

**Pull request merged**
