### PR TITLE
Add medium-down breakpoint

### PR DESCRIPTION
**Pull request by matzimowski**
closes https://github.com/brainly/style-guide/issues/348
🍈

### CODE REVIEW

**Comment by kdzwinel** [comment]
oik 🐷

**Comment by vergilius** [comment]
amazing amount of

**W** onderfull
**O** riginal
**R** etro
**K** amikaze 🚀

**Comment by matzimowski** [comment]
nice piggy

**Comment by matzimowski** [comment]
nice rocket

**Comment by vergilius** [comment]
👍

**Pull request merged**
