### PR TITLE
Added --spaced modifier for content box title/header

### LINKED ISSUE #330: Add --spaced modifier to mint-content-box__title and __header

### PR DESCRIPTION
**Pull request by mr-mig**
Fixed #330 

image

### CODE REVIEW

**Comment by aju** [comment]
I think it has wrong name it should be something like `padded-left` or something like that - what do you think ?

**Comment by mr-mig** [comment]
It is a wrong design. There should be a column from the left side, as in any media object.

Regarding the name - yes, its is kinda weird. Changing the name will be a braking change though. I'd make it a separate issue TBH

**Comment by aju** [comment]
ok

**Comment by matzimowski** [comment]
:+1:

**Pull request merged**
