### PR TITLE
Rename mint- prefix to sg-

### PR DESCRIPTION
**Pull request by matzimowski**

### CODE REVIEW

**Comment by vergilius** [comment]
🚐 👍

**Comment by matzimowski** [comment]
`sg-` stands for:

ad7781b4-208b-4f5c-90c3-f343fba5d3b8

**Comment by kdzwinel** [comment]
http://www.abbreviations.com/SG

Support Group
San Gabriel
Space Ghost
Super Glue
Star Gate
Silicon Graphics

:+1:

**Comment by aju** [comment]
yeah wut eva 👍

**Pull request merged**
