### PR TITLE
New set of subjects icons

### PR DESCRIPTION
**Pull request by burakukula**
The '3 dots' icons are used just to let market's know that they need to stop using icons that were in that places until now.
icons-sg

### CODE REVIEW

**Comment by aju** [comment]
Did you check whats the size difference (old vs new) ?

**Comment by vergilius** [comment]
I kinda dislike defs (whitespaces should be removed or indented properly)

**Comment by burakukula** [comment]
@aju gzip version of a new set of icons will have 14, the cuurent set have 19.7

**Comment by aju** [comment]
@burakukula <3

**Pull request merged**
