### PR TITLE
Added brainly tutoring logo

### PR DESCRIPTION
**Pull request by mateuszs**
Added brainly tutoring logo, regarding task: https://brainly.atlassian.net/browse/TUT-1050

image

### CODE REVIEW

**Review by coderitual — APPROVED** [review]
👍

**Comment by matzimowski** [comment]
could u provide a screenshot too, please?

**Review by matzimowski — APPROVED** [review]

**Comment by mateuszs** [comment]
> could u provide a screenshot too, please?

@matzimowski 
in description

**Comment by coderitual** [comment]
Hey @mateuszs , I have updated your branch to enable you to merge it early tomorrow - travis is super slow.

**Comment by matzimowski** [comment]
> > could u provide a screenshot too, please?
> 
> @matzimowski
> in description

fantastic, thank you!

**Pull request merged**
