### PR TITLE
Update main grey colors

### PR DESCRIPTION
**Pull request by matzimowski**
before:
screen shot 2016-06-27 at 16 26 45

after:
screen shot 2016-06-27 at 16 30 08

all components that use grey primary and secondary will be updated.

major or minor?

### CODE REVIEW

**Comment by mon29** [comment]
:+1:

**Comment by vergilius** [comment]
imho minor as classnames do not change 👍

**Comment by kdzwinel** [comment]
👍

**Comment by aju** [comment]
```
I see a red door and I want it painted gray
No colors any more, I want them to turn gray
...
```

**Pull request merged**
