### PR TITLE
Setup github actions for CI

### PR DESCRIPTION
**Pull request by coderitual**
Github Actions configuration for CI -  Travis CI replacement.

### CODE REVIEW

**Review by maciekbb — APPROVED** [review]
looks good :) 

are you going to handle copying release files to s3 in github actions as well?

**Review by radekwarisch — APPROVED** [review]
🚀

**Comment by coderitual** [comment]
@maciekbb For deployment I am going to use this repo: https://github.com/brainly/design-infra-styleguide-platform.
 with terraform configuration and GA terraform action using prepared modules from here: https://github.com/brainly/service-catalog-modules :)

**Review by Malinicz — APPROVED** [review]
👏

**Pull request merged**
